# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ad2dcb15c885f4341b38f801b5d3418448ee7f6a6bfd4fd07d096be7ae4efcf65d2231abd658b6e2afd7fe1c1ce33e3acc5ad026d48806192558fa043ffbdef

test:
  secret_key_base: 979e75e7974a89c226ae33c61145cb723a7a15eceef2329eaac9a95082062f761677c08b6a49bb9bd16ffcf2cd25312221c1c09238da26da17e8ede665f9959a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
